### ISSUE TITLE
再起動時に遅れていない分すべてを送れるようにする

### ISSUE THREAD

**Issue by Luftalian** [traP-jp/traQ-gazer#107]
一旦アプリを停止してしまうと、再起動するまでの間にtraQに投稿された投稿はDMとして通知を送ることができない。

**Comment by Luftalian** [comment]
解決案：新しいテーブルを作る

**Comment by oribe1115** [comment]
どういうデータを持つテーブルを考えていますか？

**Comment by Luftalian** [comment]
テーブル名：`time`
|last_time|
|---|
|DATETIME|
|2001-01-14 08:45|

これで、`UPDATE time SET last_time = NOW()` こうすることを考えています。

**Comment by Luftalian** [comment]
https://github.com/traP-jp/h23s_15/blob/c5e7b68decd35f30ebb95d6c741c9f89a967fad8/server/traqmessage/collect.go#L82

そして、ここの`from time.Time`にいれます。

**Comment by Luftalian** [comment]
searchに出てくるまでの時間を考えるともう少し考える必要がありそうです

**Comment by Luftalian** [comment]
テーブル名：`lastest`
|last_message|last_time|
|---|---|
|VARCHAR(36)|DATETIME|
|**********|2001-01-14 08:45|

時間でなんとなくとって、正確には最後に投稿したもの以降のものを取るのはどうでしょう？

**Comment by oribe1115** [comment]
新しくsearchのクエリを飛ばす時は最後の時間よりちょっと前の時刻で検索をかけて、実際に最後に通知を飛ばしたメッセージまではフィルターで落とす感じかな？
`last_message`のところをtraQのmessage idに、`last_time`は実行した時刻ではなく取得した中の最新メッセージの時刻にしたらいい感じになりそうです

**Comment by Pugma** [comment]
#133 で解決できたので close
