### ISSUE TITLE
登録した単語をcase insensitiveで検出したい

### ISSUE THREAD

**Issue by oribe1115** [traP-jp/traQ-gazer#109]
case insensitive: アルファベットにおいて大文字小文字の区別をしないこと

traQの投稿では細かい表記ゆれが多発するので、それをまとめて検出できると嬉しい

# 現在の実装
登録単語と完全一致するものだけ検出している

e.g. 登録単語が`traQ gazer`なら
- `traQ gazer` → :white_check_mark:
- `traq gazer` → :x:
- `traQ Gazer` → :x:

# case insentiveで検出するようにした場合
e.g. 登録単語が`traQ gazer`なら
- `traQ gazer` → :white_check_mark:
- `traq gazer` → :white_check_mark:
- `traQ Gazer` → :white_check_mark:

**Comment by oribe1115** [comment]
#115 でSQLで取得をするようになってからcase insensitiveになってると思われる

**Comment by Pugma** [comment]
PR出てるし充分そうなのでこれ閉じます
