### ISSUE TITLE
短時間で大量投稿が発生したときにポーリングと通知処理が壊れた

### ISSUE THREAD

**Issue by oribe1115** [traP-jp/traQ-gazer#127]
ログ上ではポーリングがかなりの回数行われてるだけっぽくなっているが、1件の通知対象投稿が同じ人に無限に通知され続ける事態が発生した
再起動することでとりあえず止められた
![image](https://github.com/traP-jp/traQ-gazer/assets/50443000/596059d9-3435-4d9b-877e-da5b627c7e9f)

トリガーとなった一連の投稿はここから
https://q.trap.jp/messages/1fa7b238-a5c6-4062-855c-5a352ad8d86b

**Comment by Pugma** [comment]
#128 により解決したため close
